import useSWR from "swr";
import Head from "next/head";

import { authService } from "@/services/auth-service";

import type { NextPage } from "next";

const Home: NextPage = () => {
  const { data, error } = useSWR(
    process.env.NEXT_PUBLIC_STAND_SERVICE_URL,
    async () => await authService()
  );

  return (
    <div>
      <Head>
        <title>{data?.data.messages}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold">Hello world!</h1>
        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>
      </main>
    </div>
  );
};

export default Home;
