import useSWR from "swr";
import Head from "next/head";

import { authService } from "@/services/auth-service";

import type { NextPage } from "next";

const Home: NextPage = () => {
  const { data, error } = useSWR("/api", async () => await authService());
  return (
    <div className="bg-slate-100 dark:bg-slate-800">
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center min-h-screen">
        <h1 className="text-3xl font-bold">Hello world!</h1>
        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>
      </main>
    </div>
  );
};

export default Home;
